#!/bin/zsh
# Builds the plugin against the OBS Studio that is installed on this Mac,
# without building OBS itself. Only the libobs headers are downloaded.
#
# Usage: ./build-macos-local.sh [--install]
#   --install  copy the plugin to ~/Library/Application Support/obs-studio/plugins
set -euo pipefail

cd "${0:A:h}"

PLUGIN_NAME="obs-image-reaction-ashmanix"
PLUGIN_VERSION="1.1.0"
BUNDLE_ID="com.example.${PLUGIN_NAME}"
OBS_APP="${OBS_APP:-/Applications/OBS.app}"
LIBOBS_FRAMEWORK="${OBS_APP}/Contents/Frameworks/libobs.framework"

if [[ ! -d "${LIBOBS_FRAMEWORK}" ]]; then
  echo "OBS not found at ${OBS_APP} (set OBS_APP to override)" >&2
  exit 1
fi

OBS_VERSION="$(defaults read "${OBS_APP}/Contents/Info.plist" CFBundleShortVersionString)"
DEPS_DIR=".deps/obs-studio-${OBS_VERSION}"

# libobs headers matching the installed OBS version
if [[ ! -d "${DEPS_DIR}/libobs" ]]; then
  echo "Fetching libobs ${OBS_VERSION} headers..."
  rm -rf "${DEPS_DIR}"
  git clone --quiet --depth 1 --branch "${OBS_VERSION}" -c advice.detachedHead=false --filter=blob:none --sparse \
    https://github.com/obsproject/obs-studio.git "${DEPS_DIR}"
  git -C "${DEPS_DIR}" sparse-checkout set libobs
fi

# libobs needs the SIMDe headers on Apple Silicon
SIMDE_VERSION="v0.8.2"
SIMDE_DIR=".deps/simde-${SIMDE_VERSION}"
if [[ ! -d "${SIMDE_DIR}/simde" ]]; then
  echo "Fetching SIMDe ${SIMDE_VERSION} headers..."
  rm -rf "${SIMDE_DIR}"
  git clone --quiet --depth 1 --branch "${SIMDE_VERSION}" -c advice.detachedHead=false \
    https://github.com/simd-everywhere/simde.git "${SIMDE_DIR}"
fi

# obsconfig.h is normally generated by the OBS build
mkdir -p "${DEPS_DIR}/generated"
cat > "${DEPS_DIR}/generated/obsconfig.h" <<CONFIG
#pragma once
#define OBS_DATA_PATH "../Resources"
#define OBS_PLUGIN_PATH "../PlugIns"
#define OBS_PLUGIN_DESTINATION "../PlugIns"
CONFIG

BUNDLE="build/${PLUGIN_NAME}.plugin"
rm -rf "${BUNDLE}"
mkdir -p "${BUNDLE}/Contents/MacOS" "${BUNDLE}/Contents/Resources"

echo "Building ${PLUGIN_NAME} ${PLUGIN_VERSION} for OBS ${OBS_VERSION}..."
clang -bundle -O2 -Wall -std=gnu17 \
  -mmacosx-version-min=13.0 \
  -I "${DEPS_DIR}/libobs" -I "${DEPS_DIR}/generated" -I "${SIMDE_DIR}" \
  -F "${OBS_APP}/Contents/Frameworks" -framework libobs \
  -o "${BUNDLE}/Contents/MacOS/${PLUGIN_NAME}" \
  src/image-reaction.c

cp -R data/locale "${BUNDLE}/Contents/Resources/"

cat > "${BUNDLE}/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>${PLUGIN_NAME}</string>
	<key>CFBundleIdentifier</key>
	<string>${BUNDLE_ID}</string>
	<key>CFBundleVersion</key>
	<string>${PLUGIN_VERSION}</string>
	<key>CFBundleShortVersionString</key>
	<string>${PLUGIN_VERSION}</string>
	<key>CFBundleExecutable</key>
	<string>${PLUGIN_NAME}</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>LSMinimumSystemVersion</key>
	<string>13.0</string>
</dict>
</plist>
PLIST

codesign --force --sign - "${BUNDLE}"
echo "Built ${BUNDLE}"

if [[ "${1:-}" == "--install" ]]; then
  PLUGINS_DIR="${HOME}/Library/Application Support/obs-studio/plugins"
  mkdir -p "${PLUGINS_DIR}"
  rm -rf "${PLUGINS_DIR}/${PLUGIN_NAME}.plugin"
  cp -R "${BUNDLE}" "${PLUGINS_DIR}/"
  echo "Installed to ${PLUGINS_DIR} - restart OBS to load it"
fi
